# This is a basic workflow that is manually triggered

name: workflow final unit tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: test
        uses: actions/checkout@v2.3.4
      - name: install coverage
        run: pip install coverage
      - name: Unit Test 
        run: python3 unit_test.py
      - name: Integration Test 
        run: python3 integration_test.py
      - name: Unit Test Coverage
        run: coverage run unit_test.py Cat.py Dog.py Mouse.py Animal.py && coverage report unit_test.py Cat.py Dog.py Mouse.py Animal.py
      - name: Integration Test Coverage
        run: coverage run integration_test.py Cat.py Dog.py Mouse.py Animal.py && coverage report integration_test.py Cat.py Dog.py Mouse.py Animal.py
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2.10.0
    
  
