# This is a basic workflow that is manually triggered

name: workflow final unit tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: test
        uses: actions/checkout@v2.3.4
      - name: install coverage
        run: pip install coverage
      - name: Unit Test 
        run: python3 unit_test.py
      - name: Integration Test 
        run: python3 integration_test.py
      - name: Unit Test Coverage
        run: python3 -m coverage run unit_test.py && python3 -m coverage report unit_test.py
      - name: Integration Test Coverage
        run: python3 -m coverage run integration_test.py && python3 -m coverage report integration_test.py
        
    
  
